[package]
name = "pastebin"
version = "0.1.0"
edition = "2021"

[dependencies]
#since we are working with json for S and D
serde = { version = "1.0", features = ["derive"] }
actix-web = "4.6.0"
rusqlite = "0.31.0"
rand = "0.8.5"
actix-files = "0.6.5"