[package]
name = "async-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
#help makes async and await requests
tokio = { version = "1", features = ["full"] }
