[package]
name = "extract-links"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = "0.12.4"
tokio = { version = "1", features = ["full"] }
# help select exact things from the page 
select = "0.6.0"