[package]
name = "rust-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-async-std", "tls-native-tls" ,"sqlite" ] }
async-std = "1.12.0"
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["full"] }
error-chain = "0.12.4"